<?php
// Generated by app_settings.php

define('APP_NAME', 'UKK TODOLIST');
define('BASE_URL', 'http://localhost:8002');
define('TIMEZONE', 'Asia/Jakarta');
define('UPLOAD_MAX_SIZE', '2');
define('ALLOWED_FILE_TYPES', 'jpg,jpeg,png,gif,webp');
define('MAINTENANCE_MODE', '1');
